version: '3.6'

services:
  favodemel-web:
    image: favodemel-web
    container_name: favodemel-web
    build: .
    ports:
      - 54200:80
    networks:
      - net

networks:
  net:
    driver: bridge
    external: true
