version: '3.4'

services:
  favodemel-web:
    image: favodemel-web
    container_name: favodemel-web
    build: .
    ports:
      - 4200:80
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
