version: '2'

services:
  favodemel.api:
    image: favodemelapi:dev
    container_name: FavoDeMel.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "FavoDeMel.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_favodemel.api$
    volumes:
      - D:\Pessoal\Arquitetura\Novo\favodemel-api\src\FavoDeMel.Api:/app
      - D:\Pessoal\Arquitetura\Novo\favodemel-api:/src
      - C:\Users\40923\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_favodemel.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_favodemel.api$ \"/app/bin/Debug/net5.0/FavoDeMel.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true