version: '3.6'

services:
  favodemel-api:
    ports:
      - "8080:80"
      - "44300:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44300
    container_name: favodemel-api
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: favodemel-api-db
    restart: always
    environment:
      MYSQL_DATABASE: 'favodemel-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - favodemel-api-mysql-data:/var/lib/mysql

  redis:
    image: redis:4.0.11
    container_name: favodemel-api-redis
    ports:
      - "6379:6379"
    volumes:
      - "favodemel-api-redis-data:/data"

  redis-commander:
    image: rediscommander/redis-commander
    container_name: favodemel-api-redis-commander
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: |
        no1:redis:6379:0,no2:redis:6379:1,no3:redis:6379:2
      USE_SCAN: "true"
    depends_on:
      - redis

  minio:
    container_name: favodemel-api-minio
    image: minio/minio
    volumes:
      - favodemel-api-arquivos:/favodemel-arquivos
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /favodemel-arquivos
  
  rabbitmq:
    image: "rabbitmq:3.8-management"
    container_name: favodemel-api-rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - "15672:15672"
        - "5672:5672"
    labels:
        NAME: "rabbitmq1"

volumes:
  favodemel-api-rabbitmq-data:
  favodemel-api-mysql-data:
  favodemel-api-redis-data:
  favodemel-api-arquivos: