version: '3.6'

services:
  favodemel.api:
    image: ${DOCKER_REGISTRY-}favodemelapi
    container_name: avaliacao-favodemel-api
    build:
      context: .
      dockerfile: src/FavoDeMel.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=54300
    ports:
      - "58080:80"
      - "54300:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - favodemel.api.postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:58080/health"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 60s
    networks: 
      - net

  healthcheck-ui:
    image: xabarilcoding/healthchecksui:latest
    environment:
      - Logging__LogLevel__Default=Debug
      - Logging__Loglevel__Microsoft=Warning
      - Logging__LogLevel__HealthChecks=Debug
      - ui_path=/
      - ui_api_path=/api
      - ui_webhooks_path=/webhooks
      - HealthChecksUI__HealthChecks__0__Name=favodemel-api
      - HealthChecksUI__HealthChecks__0__Uri=http://host.docker.internal:58080/healthz
    depends_on:
      - favodemel.api
    ports:
      - "5080:80"
    networks: 
      - net

  favodemel.api.postgres:
    image: postgres:11-alpine
    container_name: avaliacao-favodemel-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password_1
      - POSTGRES_DB=favodemel
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - avaliacao-favodemel-postgres-data:/var/lib/postgresql/data
    networks: 
      - net

  favodemel.api.flyway:
    image: flyway/flyway:7
    container_name: avaliacao-favodemel-flyway
    restart: on-failure
    command: -url=jdbc:postgresql://favodemel.api.postgres:5432/favodemel -schemas=migration -user=admin -password=Password_1 migrate
    environment:
      - FLYWAY_EDITION=community
    volumes:
      - ./postgresdb/scripts:/flyway/sql
    depends_on:
      - favodemel.api.postgres
      - favodemel.api
    networks: 
      - net

  favodemel.api.redis:
    image: redis:4.0.11
    container_name: avaliacao-favodemel-redis
    ports:
      - "6379:6379"
    volumes:
      - avaliacao-favodemel-redis-data:/data
    networks: 
      - net

  favodemel.api.redis-commander:
    image: rediscommander/redis-commander
    container_name: avaliacao-favodemel-redis-commander
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: |
        no1:favodemel.api.redis:6379:0,no2:favodemel.api.redis:6379:1,no3:favodemel.api.redis:6379:2
      USE_SCAN: "true"
    depends_on:
      - favodemel.api.redis
    networks: 
      - net

  favodemel.api.rabbitmq:
    image: rabbitmq:3-management
    container_name: avaliacao-favodemel-rabbitmq
    hostname: favodemel.api.rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15674:15674"
    environment:
      - DEFAULT_VHOST=/
      - DEFAULT_USER=guest
      - DEFAULT_PASS=guest
    volumes:
      - avaliacao-favodemel-rabbitmq-data:/var/lib/rabbitmq
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks: 
      - net

volumes:
  avaliacao-favodemel-rabbitmq-data:
  avaliacao-favodemel-postgres-data:
  avaliacao-favodemel-redis-data:

networks: 
  net:
    driver: bridge